### ISSUE TITLE
Add project licence to Readme

### ISSUE THREAD

**Issue by ghost** [yooksi/celestial#1]
@yooksi 

I though it best to ask you as to what licence you would like to give this project? (e.g. GPL v3)

**Comment by matshou** [comment]
Since this mod will be dependent on [TimeLib](https://github.com/yooksi/TimeLib) which is licensed under GPL v3, the following [requirement](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL) applies which stipulates that...

> ... because the program actually links to the library. As such, the terms of the GPL apply to the entire combination.

**Comment by matshou** [comment]
Why did you close this? The project license is still MIT.

**Comment by ghost** [comment]
Updated licence with commit 10dcdd83d21fdc08da72b52d8a66024d69db12d5
