### ISSUE TITLE
Decide on project title

### ISSUE THREAD

**Issue by ghost** [yooksi/celestial#3]
My suggestion for the title is **Celestial**.

It refers to something `Positioned in or relating to the sky, or outer space...`

The term directly refers to what the mod is about, without obscurity.

@yooksi What do you think? any suggestions?

**Comment by matshou** [comment]
How about **Stellar** or extending from that **StellarCraft**?

Etymology of the word:
https://en.wiktionary.org/wiki/stellar

Just a few results on CurseForge:
https://www.curseforge.com/minecraft/mc-mods/search?search=stellar

**Comment by ghost** [comment]
I'm fine with that title; although I do prefer *celestial* for a few reasons:

- Celestial has only 1 mod with the same name

- The term *stellar* refers to stars; which is not fully representative of what the mod is about.

**Comment by matshou** [comment]
> Celestial has only 1 mod with the same name

Technically there is not one mod that is called **Stellar** or **StellarCraft**, but there are mods that contain *stellar* word in their name, that shouldn't be a problem.

> The term stellar refers to stars; which is not fully representative of what the mod is about.

I thought the main premise behind the mod is the ability to affect how fast the day/night changes and transforming your solar system into a binary or even (possibly) trinary system. Having multiple moons would be just an addition to this. This is at least what we originally spoke afaik.

**Comment by ghost** [comment]
While initially the mod will need only to provide the ability to change the day/night duration; my thoughts on the its full scope is having the ability to simulate a wide variety of extraterrestrial planets, with various celestial objects; such as other planets and moons.

**Comment by matshou** [comment]
Okay fair enough. You still can't argue that *Celestial* is a more kicakss name then *StellarCraft* :stuck_out_tongue:

**Comment by ghost** [comment]
True dat 😜
